### ISSUE TITLE
Can't scroll on mobile

### ISSUE THREAD

**Issue by seanfrasure** [MrMagma/mrmagma.github.io#5]
I can't scroll any farther than this:
![img_20160418_085002](https://cloud.githubusercontent.com/assets/9723817/14604650/b4b241c8-0542-11e6-9a31-8d607fe00d3e.JPG)

**Comment by MrMagma** [comment]
Sorry for the late reply. I'll do my best to fix this over the next week or two.

There are quite a few problems with the current version of the site, namely SEO and not being very good on mobile, so I'll probably ditch the current version sometime soon, making this a non-issue (that's one way to fix it).
